# Generated by Django 5.2.13 on 2026-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(default="0000000000", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
